### ISSUE TITLE
2º meeting

### ISSUE THREAD

**Issue by cicerohen** [cicerohen/treinamento-react-redux-saga#8]
# 2º meeting do treinamento React/Redux/Saga

### Objetivo

Fomentar o aprendizado sobre React.js e tecnologias associadas, para a construção de aplicações web/mobile modernas.

### Local, data e horário

[R. Visc. de Mauá, 1940 - Meireles, Fortaleza - CE, 60125-160](https://goo.gl/maps/kN3TSg6Yu9ZVDELs6).
Número do laboratório ainda será confirmado e colocado aqui posteriormente.

22/06/2019 das 09:00 às 12:00

### Requisitos

Conhecimento prévio em Javascript e html, conhecimento básico em Git e linhas de comando. O básico de React pode ser necessário pois não será visto os conceitos tudo do zero.

Conta no github para ir mantendo um versionamento do código trabalho e assim poder dar continuidade nos estudos nos próximos eventos.

#### Equipamento

Não será necessário levar equipamento, pois o laboratório disponibilizará de computadores com internet e softwares necessários para o treinamento. Porém não é proibido levar computador pessoal, caso seja essa a preferência do participante.

### Quantidade de vagas

Até o momento estão confirmadas 15 vagas para uso de computador do laboratório.

### Código de conduta do local

Não será permitido o consumo de qualquer tipo de alimento dentro do ambiente do laboratório.

**Comment by rivajunior** [comment]
# TREINAMENTO REACT.JS

## Dia de treinamento nº 2

### Objetivo

Fomentar o aprendizado sobre React.js e tecnologias associadas, para a construção de aplicações web/mobile modernas.

### Local, data e horário

[R. Visc. de Mauá, 1940 - Meireles, Fortaleza - CE, 60125-160](https://goo.gl/maps/kN3TSg6Yu9ZVDELs6).

22/06/2019 das 09:00 às 14:00

### Requisitos

Conhecimento prévio em Javascript e html, conhecimento básico em Git e linhas de comando. O básico de React pode ser necessário pois não será visto os conceitos tudo do zero.

Conta no github para ir mantendo um versionamento do código trabalho e assim poder dar continuidade nos estudos nos próximos eventos.

#### Equipamento

Não será necessário levar equipamento, pois o laboratório disponibilizará de computadores com internet e softwares necessários para o treinamento. Porém não é proibido levar computador pessoal, caso seja essa a preferência do participante.

### Quantidade de vagas

Até o momento estão confirmadas 15 vagas para uso de computador do laboratório.

### Código de conduta do local

Não será permitido o consumo de qualquer tipo de alimento dentro do ambiente do laboratório.

**Comment by LuisEduJulio** [comment]
Bom dia! Como faço para garantir a entrada?

**Comment by machap** [comment]
Gostaria de participar. Tem algum tipo de confirmação.

**Comment by Cicero-VianaOSF** [comment]
> 
> 
> Bom dia! Como faço para garantir a entrada?

É free, mas sujeita à capacidade do laboratório.

**Comment by Cicero-VianaOSF** [comment]
> 
> 
> Gostaria de participar. Tem algum tipo de confirmação?

Neste não irá precisar. Nos próximos iremos fazer um controle melhor disso. :D

**Comment by rivajunior** [comment]
@machap @LuisEduJulio vocês podem confirmar no seguinte link https://www.facebook.com/events/726950617722705/ . Não é obrigatório, é só pra gente ter uma ideia das pessoas que vão.

**Comment by rivajunior** [comment]
Obrigado a todos que compareceram. Fiquem ligados para não perder o próximo treinamento.
